import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { Avatar, Box } from "@mui/material";
import PermanentDrawerLeft from "@/components/PermanentDrawerLeft";
import ScrollableTabsButtonPrevent from "@/components/ScrollableTabsButtonPrevent";
import { Grid } from "@mui/material";
import Typography from "@mui/material/Typography";
import theme from "@/src/theme";
import TextField from "@mui/material/TextField";
import MeetingData from "@/constants/MeetingData";
import ProjectProgress from "@/components/ProjectProgress";
import ArrowForwardIcon from '@mui/icons-material/ArrowForward';
import FilesData from "@/constants/FilesData";
import SearchSmallScreen from "@/components/SearchSmallScreen";

export default function Home() {
  return (
    <>
      <Head>
        <title>Task Manager UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Box sx={{ display: "flex" }}>
        <PermanentDrawerLeft />
        <Grid
          container
          spacing={1}
          sx={{
            bgcolor: theme.palette.tertiary.light,
            flexGrow: 1,
            display: "flex",
            justifyContent: "space-around"
          }}
        >
          <Grid item xs={12} md={5} sx={{ margin: {xs: "1rem", md: "2rem"}}}>
            <SearchSmallScreen/>
            <Box
              sx={{
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                marginBottom: "0.5rem"
              }}
            >
              <Typography
                variant="h5"
                sx={{ color: theme.palette.primary.dark, marginLeft: "0.5rem" }}
              >
                Schedule
              </Typography>
              <Typography
                variant="body2"
                sx={{ color: theme.palette.primary.light, marginRight: "0.5rem" }}
              >
                Feb 22, 2023
              </Typography>
            </Box>
            <ScrollableTabsButtonPrevent />
            <ProjectProgress/>
          </Grid>
          <Grid item xs={12} md={5} sx={{ margin: "2rem" }}>
            <Box
              sx={{
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                my: "1rem",
              }}
            >
              <TextField
                hiddenLabel
                id="filled-search"
                label="Search"
                type="search"
                size="small"
                sx={{ width: "100%", marginRight: "1rem", display: {xs: "none", md: "flex"} }}
              />
              <Avatar alt="facebook_avatar" src="/assets/Img3.jpg" sx={{display : {xs: "none", md: "flex"}}}/>
            </Box>
            <Box
              sx={{
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                marginBottom: "2rem"
              }}
            >
              <Typography
                variant="h6"
                sx={{ color: theme.palette.primary.dark }}
              >
                Meeting
              </Typography>
              <Typography
                variant="body2"
                sx={{ color: theme.palette.primary.light }}
              >
                Feb 20 - Feb 25, 2023
              </Typography>
            </Box>
            <MeetingData/>
            <Box
              sx={{
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                marginY: "2rem"
              }}
            >
              <Typography
                variant="h6"
                sx={{ color: theme.palette.primary.dark }}
              >
                Files
              </Typography>
              <Box
              sx={{
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
              }}
            >
              <Typography
                variant="body2"
                sx={{ color: theme.palette.primary.light, marginRight: "0.5rem" }}
              >
                View All
              </Typography>
              <ArrowForwardIcon sx={{ color: theme.palette.primary.light}}/>
            </Box>
            </Box>
            <FilesData/>
          </Grid>
        </Grid>
      </Box>
    </>
  );
}
