import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { Avatar, Box } from "@mui/material";
import PermanentDrawerLeft from "@/components/PermanentDrawerLeft";
import ScrollableTabsButtonPrevent from "@/components/ScrollableTabsButtonPrevent";
import { Grid } from "@mui/material";
import Typography from "@mui/material/Typography";
import theme from "@/src/theme";
import TextField from "@mui/material/TextField";
import MeetingData from "@/constants/MeetingData";
import ProjectProgress from "@/components/ProjectProgress";
import ArrowForwardIcon from "@mui/icons-material/ArrowForward";
import FilesData from "@/constants/FilesData";
import SearchSmallScreen from "@/components/SearchSmallScreen";
import { useEffect, useRef } from "react";
import { SidebarState } from "@/store/context";
import SearchIcon from "@mui/icons-material/Search";

export default function Home() {
  // const { sidebar, handleSidebar } = SidebarState();
  // console.log(sidebar)
  // console.log(handleSidebar)

  // const menuRef = useRef();

  // useEffect(() => {
  //   console.log(menuRef);
  //   document.addEventListener("mousedown", (e) => {
  //     if (!menuRef.current.contains(e.target)) {
  //       handleSidebar();
  //     }
  //   });
  // }, []);

  return (
    <>
      <Head>
        <title>Task Manager UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Box sx={{ display: "flex" }}>
        <PermanentDrawerLeft />
        <Grid
          // ref={menuRef}
          container
          spacing={1}
          sx={{
            flexGrow: 1,
            bgcolor: theme.palette.tertiary.light,
            display: "flex",
            justifyContent: "space-around",
          }}
        >
          <Grid item xs={12} md={5} sx={{ margin: { xs: "1rem", md: "2rem" } }}>
            <SearchSmallScreen />
            <Box
              sx={{
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                marginBottom: "0.5rem",
                marginX: "1rem",
              }}
            >
              <Typography
                variant="h5"
                sx={{
                  color: theme.palette.primary.dark,
                }}
              >
                Schedule
              </Typography>
              <Typography
                sx={{
                  color: theme.palette.primary.light,
                  fontSize: { xs: "0.75rem", md: "1rem" },
                }}
              >
                Feb 22, 2023
              </Typography>
            </Box>
            <ScrollableTabsButtonPrevent />
            <ProjectProgress />
          </Grid>
          <Grid item xs={12} md={5} sx={{ margin: "2rem" }}>
            <Box
              sx={{
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                margin: "1rem",
              }}
            >
              <TextField
                hiddenLabel
                id="filled-search"
                label="Search"
                type="search"
                size="small"
                sx={{
                  width: "100%",
                  marginRight: "2rem",
                  display: { xs: "none", md: "flex" },
                }}
              />
              <SearchIcon
                sx={{
                  color: theme.palette.primary.main,
                  position: "absolute",
                  right: { md: "9rem", lg: "10rem", xl: "11rem" },
                }}
              />
              <Avatar
                alt="facebook_avatar"
                src="/assets/Img3.jpg"
                sx={{ display: { xs: "none", md: "flex" } }}
              />
            </Box>
            <Box
              sx={{
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                marginBottom: "2rem",
                marginX: "1rem",
              }}
            >
              <Typography
                variant="h6"
                sx={{ color: theme.palette.primary.dark }}
              >
                Meeting
              </Typography>
              <Typography
                sx={{
                  color: theme.palette.primary.light,
                  fontSize: { xs: "0.75rem", md: "1rem" },
                }}
              >
                Feb 20 - Feb 25, 2023
              </Typography>
            </Box>
            <MeetingData />
            <Box
              sx={{
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                marginY: "2rem",
                marginX: "1rem",
              }}
            >
              <Typography
                variant="h6"
                sx={{ color: theme.palette.primary.dark }}
              >
                Files
              </Typography>
              <Box
                sx={{
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "space-between",
                }}
              >
                <Typography
                  sx={{
                    color: theme.palette.primary.light,
                    marginRight: "0.5rem",
                    fontSize: { xs: "0.75rem", md: "1rem" },
                  }}
                >
                  View All
                </Typography>
                <ArrowForwardIcon sx={{ color: theme.palette.primary.light }} />
              </Box>
            </Box>
            <FilesData />
          </Grid>
        </Grid>
      </Box>
    </>
  );
}
